/**
 * The configuration registry: every setting, declared once.
 *
 * Four consumers read this table and nothing else — commander option
 * construction (`cli/src/options.ts`), value resolution (`resolve.ts`),
 * `.env.example` and `docs/configuration.md` (`render-docs.ts`). Adding a
 * setting is therefore a one-line change that shows up on all four surfaces,
 * or fails the build.
 */
import { PIPELINE_DEFAULTS } from './defaults.js';
import type { Setting } from './types.js';

/** Commands that talk to an LLM endpoint, and so take the whole llm* group. */
const LLM_COMMANDS = ['generate', 'plan', 'resync', 'studio'] as const;

export const SETTINGS: readonly Setting[] = [
  // ── global ────────────────────────────────────────────────────────────────
  {
    key: 'logLevel',
    type: 'enum',
    choices: ['debug', 'info', 'error'],
    default: 'info',
    commands: [
      'analyze',
      'generate',
      'render',
      'skill',
      'validate',
      'plan',
      'apply',
      'rollback',
      'resync',
      'studio',
      'config',
    ],
    doc: 'log verbosity; -v/--verbose and -q/--quiet are shorthand for debug/error',
  },

  // ── llm ───────────────────────────────────────────────────────────────────
  {
    key: 'llmApiKey',
    type: 'string',
    secret: true,
    default: '',
    envAliases: ['OPENAI_API_KEY'],
    commands: [...LLM_COMMANDS],
    example: 'sk-...',
    doc: 'API key for the LLM endpoint; use EMPTY for keyless local endpoints. Never a flag and never allowed in the config file',
  },
  {
    key: 'llmModel',
    type: 'string',
    flag: '--model <id>',
    default: 'gpt-4o-mini',
    envAliases: ['OPENAI_MODEL'],
    commands: [...LLM_COMMANDS],
    doc: 'model identifier',
  },
  {
    key: 'llmBaseUrl',
    type: 'string',
    flag: '--base-url <url>',
    default: 'https://api.openai.com/v1',
    envAliases: ['OPENAI_BASE_URL'],
    commands: [...LLM_COMMANDS],
    doc: 'any OpenAI-compatible endpoint (hosted, vLLM, LiteLLM, a proxy)',
  },
  {
    key: 'llmMaxTokens',
    type: 'int',
    min: 1,
    flag: '--max-tokens <n>',
    default: 16000,
    envAliases: ['OPENAI_MAX_TOKENS'],
    commands: [...LLM_COMMANDS],
    doc: 'max output tokens per request',
  },
  {
    key: 'llmTimeout',
    type: 'int',
    min: 1,
    flag: '--timeout <sec>',
    default: 300,
    envAliases: ['OPENAI_TIMEOUT'],
    commands: [...LLM_COMMANDS],
    doc: 'per-request deadline in seconds; a stalled call is retried rather than allowed to hold a phase hostage',
  },
  {
    key: 'llmMaxRetries',
    type: 'int',
    min: 0,
    flag: '--llm-retries <n>',
    default: 6,
    commands: [...LLM_COMMANDS],
    doc: 'retry attempts per request; 0 means a single attempt',
  },
  {
    key: 'llmRetryBackoff',
    type: 'int',
    min: 0,
    flag: '--llm-retry-backoff <sec>',
    default: 3,
    commands: [...LLM_COMMANDS],
    doc: 'base backoff between retries, in seconds',
  },
  {
    key: 'llmConcurrency',
    type: 'int',
    min: 1,
    flag: '--llm-concurrency <n>',
    default: 16,
    commands: [...LLM_COMMANDS],
    doc: 'global cap on concurrent requests through one client',
  },
  {
    key: 'llmExtraBody',
    type: 'json',
    flag: '--extra-body <json>',
    envAliases: ['OPENAI_EXTRA_BODY'],
    commands: [...LLM_COMMANDS],
    example: '{"thinking":{"type":"disabled"}}',
    doc: 'vendor fields merged into every request body; model/messages/token fields cannot be overridden',
  },

  // ── shared paths ──────────────────────────────────────────────────────────
  {
    key: 'source',
    type: 'path',
    flag: '--source <dir>',
    requiredFor: ['analyze', 'generate', 'plan', 'apply'],
    commands: ['analyze', 'generate', 'plan', 'apply', 'validate', 'skill', 'rollback'],
    example: './src',
    doc: 'source root; required for analyze/generate/plan/apply, optional elsewhere (hash freshness for validate/skill, and the tree a backup belongs to for rollback)',
  },
  {
    key: 'work',
    type: 'path',
    flag: '--work <dir>',
    requiredFor: ['analyze', 'generate', 'render', 'resync'],
    commands: ['analyze', 'generate', 'render', 'resync', 'skill'],
    example: './.handbook',
    doc: 'work directory holding pipeline artifacts; optional for skill, where it adds coverage.json',
  },
  {
    key: 'lang',
    type: 'enum',
    // `auto|<every registered language>` cannot be hard-coded here: the choices
    // come from the adapter registry at option-build time (see cli/options.ts),
    // which is why this entry declares `dynamicChoices` instead of `choices`.
    choices: ['auto'],
    dynamicChoices: 'languages',
    default: 'auto',
    flag: '--lang <lang>',
    commands: ['analyze', 'generate'],
    doc: 'source language; auto detects and merges every registered language',
  },
  {
    key: 'title',
    type: 'string',
    flag: '--title <title>',
    default: 'System Handbook',
    commands: ['render', 'resync'],
    doc: 'handbook title for rendered outputs',
  },

  // ── generate ──────────────────────────────────────────────────────────────
  {
    key: 'phase',
    type: 'string',
    flag: '--phase <spec>',
    default: 'all',
    commands: ['generate'],
    doc: 'all | 1 | 2 | 2a | 2b | 2c | 3, or a comma list',
  },
  {
    key: 'strategy',
    type: 'enum',
    choices: ['file', 'member'],
    flag: '--strategy <s>',
    commands: ['generate'],
    doc: "file (default) or member; unset keeps the work dir's recorded strategy",
  },
  {
    key: 'skeleton',
    type: 'path',
    flag: '--skeleton <path>',
    commands: ['generate'],
    doc: 'user-authored skeleton.yaml, required for the member strategy',
  },
  {
    key: 'narrateLang',
    type: 'enum',
    choices: ['en', 'zh'],
    default: 'en',
    flag: '--narrate-lang <l>',
    commands: ['generate'],
    doc: 'prose language',
  },
  {
    key: 'detail',
    type: 'enum',
    choices: ['brief', 'deep'],
    default: 'brief',
    flag: '--detail <d>',
    commands: ['generate'],
    doc: 'card depth',
  },
  {
    key: 'synthMode',
    type: 'enum',
    choices: ['oneshot', 'doctor'],
    default: 'oneshot',
    flag: '--synth-mode <m>',
    commands: ['generate'],
    doc: 'skeleton synthesis mode',
  },
  {
    key: 'maxDoctorRounds',
    type: 'int',
    min: 1,
    default: PIPELINE_DEFAULTS.maxDoctorRounds,
    flag: '--max-doctor-rounds <n>',
    commands: ['generate'],
    doc: 'doctor convergence rounds',
  },
  {
    key: 'readWorkers',
    type: 'int',
    min: 1,
    default: PIPELINE_DEFAULTS.readWorkers,
    flag: '--read-workers <n>',
    commands: ['generate'],
    doc: 'concurrent card batches',
  },
  {
    key: 'readBatchSize',
    type: 'int',
    min: 1,
    flag: '--read-batch-size <n>',
    commands: ['generate'],
    doc: 'files per card batch; unset means 1 for --detail deep and 8 for brief',
  },
  {
    key: 'maxCharsPerFile',
    type: 'int',
    min: 0,
    default: PIPELINE_DEFAULTS.maxCharsPerFile,
    flag: '--max-chars-per-file <n>',
    commands: ['generate'],
    doc: 'truncate each file at n chars; 0 means no limit',
  },
  {
    key: 'assignBatchSize',
    type: 'int',
    min: 1,
    default: PIPELINE_DEFAULTS.assignBatchSize,
    flag: '--assign-batch-size <n>',
    commands: ['generate'],
    doc: 'cards per assignment batch',
  },
  {
    key: 'assignWorkers',
    type: 'int',
    min: 1,
    default: PIPELINE_DEFAULTS.assignWorkers,
    flag: '--assign-workers <n>',
    commands: ['generate'],
    doc: 'concurrent assignment batches',
  },
  {
    key: 'organizeWorkers',
    type: 'int',
    min: 1,
    default: PIPELINE_DEFAULTS.organizeWorkers,
    flag: '--organize-workers <n>',
    commands: ['generate'],
    doc: 'concurrent stage-organize calls',
  },
  {
    key: 'narrateWorkers',
    type: 'int',
    min: 1,
    default: PIPELINE_DEFAULTS.narrateWorkers,
    flag: '--narrate-workers <n>',
    commands: ['generate'],
    doc: 'concurrent narration calls',
  },
  {
    key: 'resume',
    type: 'bool',
    flag: '--resume',
    default: false,
    commands: ['generate'],
    doc: 'skip files that already have a completed card',
  },
  {
    key: 'refresh',
    type: 'bool',
    flag: '--refresh',
    default: false,
    commands: ['generate'],
    doc: 'ignore phase-3 caches',
  },
  {
    key: 'llmCache',
    type: 'bool',
    flag: '--llm-cache',
    default: false,
    commands: ['generate'],
    doc: 'cache raw LLM replies under <work>/phase3/cache; disabled by --refresh',
  },

  // ── render ────────────────────────────────────────────────────────────────
  {
    key: 'out',
    type: 'path',
    flag: '--out <dir>',
    scopedOnly: true,
    requiredFor: ['skill'],
    commands: ['render', 'skill', 'plan'],
    doc: 'output location; render defaults to <work>/handbook, plan writes a file, skill writes a directory',
  },
  {
    key: 'html',
    type: 'bool',
    flag: '--html',
    default: false,
    commands: ['render'],
    doc: 'also render the multi-page HTML site under <out>/html',
  },
  {
    key: 'htmlSingle',
    type: 'bool',
    flag: '--html-single',
    default: false,
    commands: ['render'],
    doc: 'also render a single self-contained HTML page',
  },
  {
    key: 'agentSite',
    type: 'bool',
    flag: '--agent-site',
    default: false,
    commands: ['render'],
    doc: 'also render the agent locator index under <out>/agent',
  },
  {
    key: 'llmsTxt',
    type: 'bool',
    flag: '--llms-txt',
    default: false,
    commands: ['render'],
    doc: 'also write llms.txt and llms-full.txt next to the markdown',
  },
  {
    key: 'sourceBaseUrl',
    type: 'string',
    flag: '--source-base-url <url>',
    commands: ['render'],
    doc: 'link file cards to the source at <url>/<relative path>',
  },

  // ── skill ─────────────────────────────────────────────────────────────────
  {
    key: 'handbook',
    type: 'path',
    flag: '--handbook <dir>',
    scopedOnly: true,
    requiredFor: ['skill'],
    commands: ['skill', 'plan'],
    doc: 'rendered handbook directory; required for skill, optional context for plan',
  },
  {
    key: 'name',
    type: 'string',
    flag: '--name <slug>',
    required: true,
    commands: ['skill'],
    doc: 'skill slug (lowercase-hyphen)',
  },
  {
    key: 'project',
    type: 'string',
    flag: '--project <name>',
    commands: ['skill'],
    doc: 'human project name for prose',
  },
  {
    key: 'agentDir',
    type: 'path',
    flag: '--agent-dir <dir>',
    commands: ['skill'],
    doc: 'rendered agent locator site; ships under references/agent/',
  },
  {
    key: 'bodyLang',
    type: 'enum',
    choices: ['en', 'zh'],
    default: 'en',
    flag: '--lang <l>',
    scopedOnly: true,
    commands: ['skill'],
    doc: 'SKILL.md body language; frontmatter stays English for routing',
  },

  // ── validate ──────────────────────────────────────────────────────────────
  {
    key: 'skill',
    type: 'path',
    flag: '--skill <dir>',
    required: true,
    commands: ['validate'],
    doc: 'skill directory to validate',
  },

  // ── plan ──────────────────────────────────────────────────────────────────
  {
    key: 'request',
    type: 'string',
    flag: '--request <text>',
    required: true,
    commands: ['plan'],
    doc: 'the natural-language change request',
  },
  {
    key: 'maxTurns',
    type: 'int',
    min: 1,
    default: 30,
    flag: '--max-turns <n>',
    commands: ['plan'],
    doc: 'agent turn budget',
  },

  // ── apply / rollback ──────────────────────────────────────────────────────
  {
    key: 'plan',
    type: 'path',
    flag: '--plan <file>',
    required: true,
    commands: ['apply'],
    doc: 'plan file produced by `handbook plan`',
  },
  {
    key: 'dryRun',
    type: 'bool',
    flag: '--dry-run',
    default: false,
    commands: ['apply'],
    doc: 'verify only, never write',
  },
  {
    key: 'backupRoot',
    type: 'path',
    flag: '--backup-root <dir>',
    commands: ['apply'],
    doc: 'where backups go; defaults to <source>/.handbook-patches',
  },
  {
    key: 'backup',
    type: 'path',
    flag: '--backup <dir>',
    required: true,
    commands: ['rollback'],
    doc: 'backup directory containing manifest.json',
  },
  {
    key: 'force',
    type: 'bool',
    flag: '--force',
    default: false,
    commands: ['rollback'],
    doc: 'restore even files that changed after the patch',
  },

  // ── resync ────────────────────────────────────────────────────────────────
  {
    key: 'case',
    type: 'path',
    flag: '--case <dir>',
    required: true,
    commands: ['resync'],
    doc: 'case directory: edited/ + plan.md + change.diff',
  },
  {
    key: 'useLlm',
    type: 'bool',
    flag: '--no-llm',
    negated: true,
    default: true,
    commands: ['resync'],
    doc: 'set false for a structural refresh only, with prose marked stale',
  },
  {
    key: 'refreshRendered',
    type: 'bool',
    flag: '--no-render',
    negated: true,
    default: true,
    commands: ['resync'],
    doc: 'set false to skip refreshing already-rendered outputs under <work>/handbook',
  },
  {
    key: 'corrections',
    type: 'path',
    flag: '--corrections <file>',
    commands: ['resync'],
    doc: 'agent-reported corrections.jsonl; its files widen the refresh set',
  },
  {
    key: 'cardDetail',
    type: 'enum',
    choices: ['brief', 'deep'],
    flag: '--detail <d>',
    scopedOnly: true,
    commands: ['resync'],
    doc: 'card depth for regenerated cards; unset matches the existing handbook',
  },
  {
    key: 'proseLang',
    type: 'enum',
    choices: ['en', 'zh'],
    flag: '--narrate-lang <l>',
    scopedOnly: true,
    commands: ['resync'],
    doc: 'prose language for regenerated cards; unset matches the existing handbook',
  },

  // ── studio ────────────────────────────────────────────────────────────────
  {
    key: 'port',
    type: 'int',
    min: 1,
    default: 4860,
    flag: '--port <n>',
    commands: ['studio'],
    doc: 'port to listen on; binds 127.0.0.1 only',
  },
  {
    key: 'stateDir',
    type: 'path',
    flag: '--state-dir <dir>',
    commands: ['studio'],
    doc: 'where studio.json and managed work dirs live; defaults to $HOME/.handbook-studio',
  },

  // ── config ────────────────────────────────────────────────────────────────
  {
    key: 'forCommand',
    type: 'string',
    flag: '--command <name>',
    commands: ['config'],
    doc: "show only the settings that apply to this subcommand; its env/file/default layers are inspectable here, but that command's own flags are not (pass them to the command itself)",
  },
  {
    key: 'json',
    type: 'bool',
    flag: '--json',
    default: false,
    commands: ['config'],
    doc: 'machine-readable output',
  },
  {
    key: 'check',
    type: 'bool',
    flag: '--check',
    default: false,
    commands: ['config'],
    doc: 'validate only; exit non-zero if anything is invalid or missing',
  },
];

export function settingsFor(command: string): readonly Setting[] {
  return SETTINGS.filter((s) => s.commands.includes(command));
}

export function settingByKey(key: string): Setting | undefined {
  return SETTINGS.find((s) => s.key === key);
}

/** Every key that applies to a command, in declaration order — including the
 *  pass-through ones that resolved to nothing, whose absence is information. */
export function keysFor(command: string): string[] {
  return settingsFor(command).map((s) => s.key);
}
