/**
 * Renders the three generated configuration surfaces — `.env.example`,
 * `docs/configuration.md`, `handbook.config.example.yaml` — from `SETTINGS`
 * and nothing else, so none of them can say something the registry does not.
 *
 * `scripts/gen-config-docs.mjs` writes what these functions return, and the
 * drift test in `packages/cli` imports the same functions and compares their
 * output to the checked-in files byte for byte. A generator and a checker
 * that could disagree would defeat the point, so every string below must be
 * derived from a `Setting` field — never a hand-typed default, example, or
 * language name.
 *
 * One deliberate exception to "derive everything": `Setting.example` is, by
 * its own doc comment in `types.ts`, a placeholder for `.env.example` only.
 * `renderConfigDocs` and `renderConfigExampleYaml` read `setting.default`
 * exclusively, so a setting with an `example` but no `default` (`source`,
 * `work`, `llmExtraBody`) still shows up there as unset — exactly the
 * pass-through behaviour decisions item 5 asks for, and the same reason
 * `readBatchSize`, `cardDetail` and `proseLang` show up unset too, even
 * though none of those three carries an `example` at all.
 */
import { envName, fileKeyCandidates, scopedEnvName } from './names.js';
import { SETTINGS, settingByKey, settingsFor } from './registry.js';
import type { Setting } from './types.js';

const ALL_COMMANDS: readonly string[] = [...new Set(SETTINGS.flatMap((s) => s.commands))];

/** Escapes a value that lands inside a markdown table cell. */
function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

/**
 * The value `.env.example` shows as a placeholder — `example` first (it
 * exists precisely to give a better placeholder than an empty-string or
 * absent default would), then the real default, then nothing at all for a
 * genuine pass-through.
 */
function envDisplayValue(setting: Setting): string | undefined {
  if (setting.example !== undefined) return setting.example;
  if (setting.default !== undefined) return String(setting.default);
  return undefined;
}

/** `llmMaxTokens` → `maxTokens`: the leaf name once the `llm` group owns the prefix. */
function stripLlmPrefix(key: string): string {
  const rest = key.slice(3);
  return rest.length === 0 ? rest : rest.charAt(0).toLowerCase() + rest.slice(1);
}

/**
 * True for the settings that share the literal `llm*` prefix *and* are not
 * scoped to a single command — the one semantic group named in the brief
 * (`llmModel` → `llm: { model }`). A setting scoped to exactly one command
 * (e.g. `llmCache`, generate-only) nests under that command instead; see
 * `renderConfigExampleYaml`.
 */
function isLlmGroupMember(setting: Setting): boolean {
  return /^llm[A-Z]/.test(setting.key) && setting.commands.length > 1;
}

// ─────────────────────────────────────────────────────────────────────────
// .env.example
// ─────────────────────────────────────────────────────────────────────────

export function renderEnvExample(): string {
  const lines: string[] = [
    '# Copy to .env (git-ignored) — the `handbook` CLI auto-loads ./.env from the',
    '# directory you run it in. Shell environment variables always win over this file.',
    '#',
    '# --env <name> (or HANDBOOK_ENV) selects a per-environment cascade instead, highest',
    '# precedence first: .env.<name>.local, .env.<name>, .env.local, .env — the first file',
    '# to set a key wins, and the shell still wins over all of them. With no --env and no',
    '# HANDBOOK_ENV, only .env.local and .env load — exactly what loaded before this cascade',
    '# existed, so an existing setup with no .env.local sees no change at all.',
    '#',
    '# Generated by `pnpm run config:docs` from the settings registry — do not hand-edit;',
    '# a hand-edit fails packages/cli/src/docs-drift.test.ts, which names this command as',
    '# the fix. See docs/configuration.md for the full reference.',
  ];

  let groupKey: string | undefined;
  for (const setting of SETTINGS) {
    const thisGroupKey = setting.commands.join(',');
    if (thisGroupKey !== groupKey) {
      lines.push('', `# ── ${setting.commands.join(', ')} ──`);
      groupKey = thisGroupKey;
    }

    lines.push(`# ${setting.doc}`);
    if (setting.secret) {
      lines.push('# secret — must never appear in a config file; set it here or in the shell only');
    }

    const value = envDisplayValue(setting);
    const unsetNote = ' (no default — see the comment above)';

    if (setting.scopedOnly) {
      // Semantics differ per command, so only the scoped name is ever valid;
      // a flat name here would silently be read by nothing.
      for (const command of setting.commands) {
        const name = scopedEnvName(command, setting.key);
        lines.push(value === undefined ? `# ${name}${unsetNote}` : `#${name}=${value}`);
      }
      continue;
    }

    const primary = envName(setting.key);
    const aliases = setting.envAliases ?? [];

    if (setting.secret && aliases.length > 0) {
      // Every line here stays commented, vendor alias included: copying this
      // file to `.env` must not silently supply a placeholder API key. An
      // uncommented `OPENAI_API_KEY=sk-...` would satisfy the client's
      // `if (!apiKey)` guard, trading a clear "no API key" error for a raw
      // 401 from the provider.
      const [vendor, ...rest] = aliases as [string, ...string[]];
      lines.push(value === undefined ? `# ${vendor}${unsetNote}` : `#${vendor}=${value}`);
      lines.push(value === undefined ? `# ${primary}${unsetNote}` : `#${primary}=${value}`);
      for (const alias of rest) {
        lines.push(value === undefined ? `# ${alias}${unsetNote}` : `#${alias}=${value}`);
      }
    } else {
      lines.push(value === undefined ? `# ${primary}${unsetNote}` : `#${primary}=${value}`);
      for (const alias of aliases) {
        lines.push(value === undefined ? `# ${alias}${unsetNote}` : `#${alias}=${value}`);
      }
    }
  }

  return `${lines.join('\n')}\n`;
}

// ─────────────────────────────────────────────────────────────────────────
// docs/configuration.md
// ─────────────────────────────────────────────────────────────────────────

function typeCell(setting: Setting): string {
  if (setting.type !== 'enum') return setting.type;
  if (setting.dynamicChoices === 'languages') {
    // The adapter registry lives in @handbook/analyzer, which this package
    // must not depend on — so the choice list is described, not enumerated.
    return 'enum (`auto`, plus any registered language)';
  }
  return `enum (${escapeCell((setting.choices ?? []).join('|'))})`;
}

function defaultCell(setting: Setting, command: string): string {
  if (setting.default !== undefined) {
    // A bare pair of backticks around an empty string (llmApiKey's default)
    // is an ambiguous, easy-to-misrender GFM construct — show the emptiness
    // instead of hiding it in whitespace no reader can see.
    const text = String(setting.default);
    return text === '' ? '`""` (empty)' : `\`${escapeCell(text)}\``;
  }
  if (setting.required || setting.requiredFor?.includes(command)) return 'required';
  return '—';
}

function envCell(command: string, setting: Setting): string {
  if (setting.scopedOnly) return `\`${scopedEnvName(command, setting.key)}\` *(scoped)*`;
  const names = [envName(setting.key), ...(setting.envAliases ?? [])];
  return names.map((n) => `\`${n}\``).join(', ');
}

function row(command: string, setting: Setting): string {
  const cells = [
    `\`${setting.key}\``,
    setting.flag ? `\`${setting.flag}\`` : '—',
    envCell(command, setting),
    typeCell(setting),
    defaultCell(setting, command),
    escapeCell(setting.doc),
  ];
  return `| ${cells.join(' | ')} |`;
}

export function renderConfigDocs(): string {
  const lines: string[] = [
    '# Configuration reference',
    '',
    'Generated by `pnpm run config:docs` from the settings registry — do not hand-edit; ' +
      'packages/cli/src/docs-drift.test.ts fails the build if this drifts from `SETTINGS`.',
    '',
    '## Precedence',
    '',
    'Every setting resolves through the same layers, highest priority first: **flag** > ' +
      '**shell env** > **`.env`** > **`handbook.config.yaml`** > **default**. The first layer ' +
      'that supplies a value wins and every layer below it is ignored for that setting. Run ' +
      '`handbook config` — or `handbook config --command <name>` to see one subcommand only — ' +
      'to check what actually resolved and which layer it came from.',
    '',
    '## Naming',
    '',
    'One camelCase `key` in the registry drives all three surfaces at once: a flag, an ' +
      'environment variable, and a config-file key. Prefixing any of them with a command name ' +
      'scopes that surface to one subcommand, and it is the same transform on all three — ' +
      '`HANDBOOK_<KEY>` becomes `HANDBOOK_<COMMAND>_<KEY>`, and `key` becomes `<command>Key` ' +
      'whether written flat or nested one level under `<command>:`. A setting marked ' +
      '*(scoped)* below only accepts the prefixed env name, because its meaning changes per ' +
      'command (`--out`, `--lang` in the skill package).',
    '',
    '## Bootstrap',
    '',
    'Three top-level settings point at the layers above, and are themselves outside the ' +
      'registry, resolved once before every other setting — which is also why none of them ' +
      'can be set by the thing they load: an `--env` key inside `handbook.config.yaml`, an ' +
      '`--env-file` line inside `.env`, or a `--config` key inside that same file would have ' +
      'nothing left to read it.',
    '',
    '- `--env <name>` (or `HANDBOOK_ENV`) selects a per-environment cascade — the only one of ' +
      'the three with both a flag and an environment-variable form, since it names an ' +
      'environment rather than pointing at one exact file.',
    '- `--env-file <path>` loads exactly that one file, bypassing the cascade below.',
    '- `--config <path>` names one exact config file, bypassing the environment-aware ' +
      'discovery below (default: the nearest `handbook.config.yaml`-family file found by ' +
      'walking up from the working directory, stopping at a repo boundary).',
    '',
    '### The `.env` cascade',
    '',
    'With no `--env-file`, the CLI loads a cascade of `.env*` files instead of one fixed ' +
      'file, highest precedence first. The existing `applyEnvFile` rule — never override a ' +
      'key already set — is what makes a cascade nothing more than "call it in this order, ' +
      'first file to set a key wins":',
    '',
    '| # | file | who | scope | committed? |',
    '| --- | --- | --- | --- | --- |',
    '| 1 | shell environment | — | — | always wins |',
    '| 2 | `.env.<name>.local` | personal | this environment only | no (gitignored) |',
    '| 3 | `.env.<name>` | team | this environment only | yes |',
    '| 4 | `.env.local` | personal | every environment | no (gitignored) |',
    '| 5 | `.env` | team | baseline | yes |',
    '',
    'Rows 2 and 3 only apply when `--env`/`HANDBOOK_ENV` names an environment. **With ' +
      'neither set, only rows 4 and 5 load — exactly what loaded before this cascade ' +
      'existed, so an existing setup with no `.env.local` sees no change at all.**',
    '',
    '### Config-file discovery with an environment',
    '',
    '`--config` aside, discovery still walks up from the working directory and stops at a ' +
      'repo boundary, but at every directory visited it now checks first for ' +
      '`handbook.config.<name>.{yaml,yml,json}` (only when an environment is named) before ' +
      'the plain `handbook.config.yaml` et al. — so a named file always wins over a plain ' +
      'file sitting in that same directory, even when a plain file exists at a level closer ' +
      'to the working directory. With no environment named, discovery is unchanged.',
    '',
    'Run `handbook config` to see which environment is active and exactly which files it ' +
      'loaded, in precedence order — a cascade on top of four value layers is too many ' +
      'possible sources to track from memory, and a layer this command cannot show is no ' +
      'different from a layer that does not work.',
    '',
  ];

  // Worked example, entirely derived from one real setting — never hand-typed.
  const example = settingByKey('readWorkers');
  if (example) {
    const command = example.commands[0] ?? 'generate';
    const flatEnv = envName(example.key);
    const scopedEnv = scopedEnvName(command, example.key);
    const candidates = fileKeyCandidates(command, example);
    const scopedFileKey = candidates[0];
    const flatFileKey = candidates[1] ?? candidates[0];
    lines.push(
      `Worked example for \`${example.key}\` (flag \`${example.flag}\`, default ` +
        `\`${String(example.default)}\`):`,
      '',
      '| surface | flat | scoped to `' + command + '` |',
      '| --- | --- | --- |',
      `| env | \`${flatEnv}\` | \`${scopedEnv}\` |`,
      `| \`handbook.config.yaml\` key | \`${flatFileKey}\` | \`${scopedFileKey}\` |`,
      '',
      `The config-file forms are interchangeable: a flat \`${flatFileKey}: ...\` and a nested ` +
        `\`${command}: { ${example.key}: ... }\` mean the same thing, because the file is ` +
        'flattened by the same camelCase join before it is read.',
      '',
    );
  }

  for (const command of ALL_COMMANDS) {
    lines.push(
      `## \`${command}\``,
      '',
      '| key | flag | env | type | default | doc |',
      '| --- | --- | --- | --- | --- | --- |',
    );
    for (const setting of settingsFor(command)) {
      lines.push(row(command, setting));
    }
    lines.push('');
  }

  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}

// ─────────────────────────────────────────────────────────────────────────
// handbook.config.example.yaml
// ─────────────────────────────────────────────────────────────────────────

interface YamlEntry {
  readonly leaf: string;
  readonly setting: Setting;
}

/** Renders a scalar exactly as YAML would read it back. */
function yamlScalar(value: string | number | boolean): string {
  if (typeof value !== 'string') return String(value);
  // Bare is fine for the plain, punctuation-light values every current
  // default happens to be; anything else gets a quoted, JSON-safe fallback
  // rather than risking a value YAML would parse differently than intended.
  return value !== '' && /^[\w./:-]+$/.test(value) ? value : JSON.stringify(value);
}

function requiredNote(setting: Setting, command?: string): string {
  if (command !== undefined) {
    return setting.required || setting.requiredFor?.includes(command) ? ' (required)' : '';
  }
  if (setting.required) return ' (required)';
  if (setting.requiredFor?.length) return ` (required for: ${setting.requiredFor.join(', ')})`;
  return '';
}

export function renderConfigExampleYaml(): string {
  const sections = new Map<string, YamlEntry[]>();
  const flatEntries: YamlEntry[] = [];

  const addTo = (section: string, leaf: string, setting: Setting): void => {
    const entries = sections.get(section) ?? [];
    entries.push({ leaf, setting });
    sections.set(section, entries);
  };

  for (const setting of SETTINGS) {
    // Never a flag, never a config-file key — see file.ts, which throws if
    // one turns up in a real handbook.config.yaml.
    if (setting.secret) continue;

    if (setting.scopedOnly) {
      // The flat key is not a valid lookup for these (see fileKeyCandidates),
      // so every command that shares one gets its own scoped entry.
      for (const command of setting.commands) addTo(command, setting.key, setting);
    } else if (isLlmGroupMember(setting)) {
      addTo('llm', stripLlmPrefix(setting.key), setting);
    } else if (setting.commands.length === 1) {
      addTo(setting.commands[0] as string, setting.key, setting);
    } else {
      flatEntries.push({ leaf: setting.key, setting });
    }
  }

  const lines: string[] = [
    '# Every non-secret setting, nested by command (or by the shared `llm` group).',
    '# Generated by `pnpm run config:docs` — hand-editing this file fails',
    '# packages/cli/src/docs-drift.test.ts, which names the regeneration command.',
    '#',
    '# This file is not auto-loaded (discovery looks for handbook.config.yaml/.yml/.json);',
    '# copy what you need into one of those and edit it. Any key below may also be',
    '# written flat instead of nested — e.g. `llmModel: gpt-4o-mini` instead of',
    '# `llm: { model: gpt-4o-mini }` — both flatten to the exact same setting.',
    '#',
    '# A key shown with a value is its built-in default. A key with no value has none —',
    "# either it's resolved elsewhere (see its comment) or it must be supplied.",
    '',
  ];

  const emit = (entry: YamlEntry, indent: string, command?: string): void => {
    lines.push(`${indent}# ${entry.setting.doc}${requiredNote(entry.setting, command)}`);
    if (entry.setting.default !== undefined) {
      lines.push(`${indent}${entry.leaf}: ${yamlScalar(entry.setting.default)}`);
    } else {
      lines.push(`${indent}# ${entry.leaf}:`);
    }
  };

  for (const entry of flatEntries) emit(entry, '');

  for (const [section, entries] of sections) {
    lines.push('', `${section}:`);
    for (const entry of entries) emit(entry, '  ', section);
  }

  return `${lines.join('\n')}\n`;
}
